version: '3.8'

services:
  nala-coder:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./configs:/app/configs
      - ./storage:/app/storage
      - ./prompts:/app/prompts
      - ./logs:/app/logs
    environment:
      - LLM_DEFAULT_PROVIDER=openai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加Ollama服务
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama_data: